name: API  Workflow

on:
  workflow_dispatch:
    inputs:
      id:
        description: 'Task Id'
        required: true
        default: '1'

jobs:
  Api_job:
    runs-on: ubuntu-latest
    steps:
      - name: Call REST API
        run: curl -s https://jsonplaceholder.typicode.com/todos/${{ github.event.inputs.id }}

      - name: Greeting 
        run: echo "Bye Bibek"