name: API  Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Path to list'
        required: true
        default: '/etc'

jobs:
  Api_job:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run:  ls -ltr ${{ inputs.name }}
        env:
          name: ${{ github.event.inputs.name }}

      - name: Greeting 
        run: echo "Bye Bibek"
        env:
          name: ${{ github.event.inputs.name }}