name: API Workflow

on:
  workflow_dispatch:
    inputs:
      id:
        description: 'Task Id'
        required: true
        default: '1'

jobs:
  Api_job:
    runs-on: ubuntu-latest
    steps:
      - name: Call REST API
        run: |
          response=$(curl -s https://jsonplaceholder.typicode.com/todos/${{ github.event.inputs.id }})
          echo "$response"
          completed=$(echo "$response" | jq -r '.completed')
          if [ "$completed" = "false" ]; then
            echo "Task is not completed"
            exit 1
          fi

      - name: Greeting
        run: echo "Good Job! You have completed the action item"